# This code generated by Nail Tosun and under licenced by PATATES Licence
# %%
from builtins import int
import time
import xlrd
import xlwt
import format
import pandas as pd

open_workbook = xlwt.Workbook(encoding="utf-8")
worksheet = open_workbook.add_sheet("ORTAK_BILGI", cell_overwrite_ok=True)
KCETAS_ay= []
KCETAS_DAIRE_NO = []
KCETAS_BINA_NO = []
KCETAS_SOKAK_Isim = []
KCETAS_MAHALLE_Isim = []
KCETAS_ADRES_List = []
KCETAS_ADRES = []
KCETAS_ABONE_TIPI = []
KCETAS_ABONE_NO_TIPI = []
KCETAS_ABONE_NO = []
KCETAS_AKTIFTUK = []
KCETAS_ORTALAMA = []
KCETAS_AY = []
KCETAS_ABONE_NO_TIPI_CON = []
KCETAS_ABONE_NO_TIPI_all = []
KCETAS_ABONE_NO_TIPI_List = []
KCETAS_first_col=[]

class Kcedas(object):
    def __init__(self, adres, abone_no, abone_tip, aktiftuk, ortalama, kesim):
        self.adres = adres
        self.abone_no = abone_no
        self.abone_tip = abone_tip
        self.aktiftuk = aktiftuk
        self.ortalama = ortalama
        self.kesim = kesim

AY = ['OCAK', 'ŞUBAT', 'MART', 'NİSAN', 'MAYIS', 'HAZİRAN', 'TEMMUZ', 'AĞUSTOS', 'EYLÜL', 'EKİM', 'KASIM', 'ARALIK']

path = r'C:\Users\nailt\Downloads\kilicaslan2_rev.xlsx'
file_read = open (path, 'r')
excel_data = file_read.readlines
wb = xlrd.open_workbook(path)
sheet_names = wb.sheet_names()

# For multiple sheets this approach can be used but not most efficient.
# %%
for sheet in wb.sheets():
    nrows = sheet.nrows
    ncols = sheet.ncols
    dataframe = []
    for row in range (nrows):
        row_carrier = []
        for col in range (ncols):
            value_cell = sheet.cell(row, col).value
            try:
                value_cell = value_cell
            except ValueError:
                pass
            finally:
                row_carrier.append(value_cell)
        df_row = Kcedas(*row_carrier)
        dataframe.append(df_row)
# %%
df_row.kesim

KCETAS_KESIM = []
for df_row in dataframe:
    if df_row.kesim != '':
        KCETAS_KESIM.append(df_row.kesim)
df = pd.DataFrame(KCETAS_KESIM)
df
df.to_csv('ildem_kesim.csv',index=False)
KCETAS_ABONE_TIPI = []
df_row.abone_tip
for df_row in dataframe:
    if df_row.abone_tip != '':
        KCETAS_ABONE_TIPI.append(df_row.abone_tip)
df = pd.DataFrame(KCETAS_ABONE_TIPI)
df.to_csv('ildemtipi.csv',index=False)
'''
for df_row in dataframe:
    KCETAS_ADRES.append(df_row.adres)
    KCETAS_first_col.append(df_row.adres)
    if df_row.aktiftuk != '':
        KCETAS_AKTIFTUK.append(df_row.aktiftuk)
    if df_row.ortalama !='':
        KCETAS_ORTALAMA.append(df_row.ortalama)
    if df_row.adres in AY:
        KCETAS_AY.append(df_row.adres)
        KCETAS_ADRES.remove(df_row.adres)
    if df_row.abone_no != '' and df_row.abone_tip != '':
        KCETAS_ABONE_NO_TIPI.append([df_row.abone_no, df_row.abone_tip])
        KCETAS_ABONE_NO.append(df_row.abone_no)
# %%
for abonenotip in KCETAS_ABONE_NO_TIPI:
    if abonenotip not in KCETAS_ABONE_NO_TIPI_all:
        KCETAS_ABONE_NO_TIPI_all.append(abonenotip)
i = 0
counter = 0
for item in KCETAS_ABONE_NO_TIPI_all:
    if item[i] == item[i+1]:
        counter = counter + 1
    if i == len(KCETAS_ABONE_NO_TIPI_all)-1:
        break
KCETAS_ABONE_NO_TIPI_all_plus1 = [x for x in KCETAS_ABONE_NO_TIPI_all]
KCETAS_ABONE_NO_TIPI_all_plus1.append(KCETAS_ABONE_NO_TIPI_all_plus1[0])
i = 1
for item in KCETAS_ABONE_NO_TIPI_all:
    if item[0] != KCETAS_ABONE_NO_TIPI_all_plus1[i][0]:
        KCETAS_ABONE_NO_TIPI_List.append(item)
    i = i + 1

KCETAS_ADRES
# %%
for patates in KCETAS_first_col:
    try:
        if 'SEMT: ' in patates:
            KCETAS_MAHALLE_Isim.append(patates)
        elif 'CADDESOKAK: ' in patates:
            KCETAS_SOKAK_Isim.append(patates)
        elif 'BINA: ' in patates:
            KCETAS_BINA_NO.append(patates)
        elif 'DAIRENO: ' in patates:
            KCETAS_DAIRE_NO.append(patates)
        elif patates in AY:
            KCETAS_ay.append(patates)
            KCETAS_ADRES_List.append([KCETAS_ay[-1],KCETAS_MAHALLE_Isim[-1], KCETAS_SOKAK_Isim[-1], KCETAS_BINA_NO[-1], KCETAS_DAIRE_NO[-1]])

    except:
        print('KCETAS adres bilgilerini kontrol et!')
KCETAS_ADRES_List
df = pd.DataFrame(KCETAS_ADRES_List)
df.to_csv('adres_list_ildem.csv',index = False)

len(KCETAS_ABONE_NO_TIPI_List)
len(KCETAS_AY)
concatADRES = ['ADRES']
for i in range(len(KCETAS_ADRES_List)):
    concatADRES.append(KCETAS_ADRES_List[i][1]+KCETAS_ADRES_List[i][2]+KCETAS_ADRES_List[i][3]+KCETAS_ADRES_List[i][4])
df = pd.DataFrame(KCETAS_AKTIFTUK)

df.to_csv('.csv',index = False)
